server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: academic-events-api
  jackson:
    time-zone: America/Guayaquil
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:academic_events_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration-ms: 900000 # 15 minutos
  refresh-token-expiration-ms: 604800000 # 7 días

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    